# Generated by Django 3.0.6 on 2020-05-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PATIENT', '0001_initial'),
        ('DOCTER', '0001_initial'),
        ('COMMON_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='docterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.Docter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.Patient'),
        ),
    ]
