# Generated by Django 3.0.6 on 2020-05-24 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PATIENT', '0001_initial'),
        ('COMMON_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('blood', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=0)),
                ('department', models.CharField(default='', max_length=30)),
                ('attendance', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=10000)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('prescripted_date', models.DateField(auto_now=True)),
                ('outstanding', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.Appointment')),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.Docter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.Patient')),
            ],
        ),
    ]
