# Generated by Django 3.0.6 on 2020-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription2',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
